### ISSUE TITLE
NasdaqDataLink() errors: resource is no longer available

### ISSUE THREAD

**Issue by joshuaulrich** [Nasdaq/data-link-r#1]
All the calls I've tried fail with

> Error: Resource is no longer available. Path: /api/v3/datasets/{data-source}/{series}

For example:

```r
x <- NasdaqDataLink::NasdaqDataLink("NSE/OIL")
## Error: Resource is no longer available. Path: /api/v3/datasets/NSE/OIL
```

**Comment by clientsuccessnasdaq** [comment]
-- Please reply above this line --


Dear Nasdaq/data-Link-R,

Thank you for contacting the Nasdaq Data Client Success Team. 

Your email is very important to us. Urgent production issues will be
addressed as soon as possible during the hours of 4am to 6pm ET Monday
to Friday.

To efficiently support your request, please include relevant details
such as the data product/feed you are inquiring about.

Kind regards,
Nasdaq Data Client Success

 [1]


Links:
------
[1] https://www.nasdaq.com/

**Comment by clientsuccessnasdaq** [comment]
-- Please reply above this line --


            Hi there,

Thanks for reaching out.

Please note this free product has been deprecated and is no longer
supported on Nasdaq Data Link.

Best regards,
Nasdaq Data Link Client Success

KIM LIRA
 Nasdaq Data Client Success 

  [1]

How would you rate my reply?
Great [2]    Okay [3]    Not Good [4]


Links:
------
[1] https://www.nasdaq.com/
[2]
https://secure.helpscout.net/satisfaction/740633668/record/8257517337/1/
[3]
https://secure.helpscout.net/satisfaction/740633668/record/8257517337/2/
[4]
https://secure.helpscout.net/satisfaction/740633668/record/8257517337/3/

**Comment by joshuaulrich** [comment]
> Please note this free product has been deprecated and is no longer supported on Nasdaq Data Link.

Then you should remove those examples from the documentation in this package, the Quandl package, and all the references on your websites. Otherwise you are misleading the public and potential users.
